using BlazorControls.Components;

using Shouldly;

namespace BlazorControls.Components.Tests
{
	/// <summary>
	/// A suite of geometry‑focused tests validating the SVG path output
	/// generated by <see cref="DonutSlice"/>. These tests ensure correct
	/// construction of inner/outer arcs, pie vs donut behavior, and
	/// full‑circle rendering logic.
	/// </summary>
	public class DonutChartGeometryTests
	{
		/// <summary>
		/// Ensures that donut slices include both the outer arc
		/// (radius = outer radius) and the inner arc (radius = inner radius).
		/// </summary>
		[Fact]
		public void DonutPath_ContainsInnerAndOuterArcs()
		{
			var slice = new DonutSlice("Donut", 50, 0, 90, 90, 70, "#0000FF");
			var path = slice.PathData;

			path.ShouldContain("A 90 90");
			path.ShouldContain("A 70 70");
		}

		/// <summary>
		/// Verifies that donut slices do not begin at the chart center,
		/// which would indicate incorrect path construction.
		/// </summary>
		[Fact]
		public void DonutPath_DoesNotStartAtCenter()
		{
			var slice = new DonutSlice("Donut", 10, 0, 60, 90, 70, "#123456");
			slice.PathData.ShouldNotStartWith("M 100 100");
		}

		/// <summary>
		/// Confirms that a full‑circle donut slice uses two outer arcs
		/// and two inner arcs to complete the shape.
		/// </summary>
		[Fact]
		public void FullCircleDonut_UsesTwoInnerAndTwoOuterArcs()
		{
			var slice = new DonutSlice("Full", 100, 0, 360, 90, 70, "#654321");
			var path = slice.PathData;

			(path.Split("A 90 90").Length - 1).ShouldBe(2);
			(path.Split("A 70 70").Length - 1).ShouldBe(2);
		}

		/// <summary>
		/// Ensures that a full‑circle pie slice (inner radius = 0)
		/// uses exactly two outer arcs to complete the circle.
		/// </summary>
		[Fact]
		public void FullCirclePie_UsesTwoOuterArcs()
		{
			var slice = new DonutSlice("FullPie", 100, 0, 360, 90, 0, "#123456");
			(slice.PathData.Split("A 90 90").Length - 1).ShouldBe(2);
		}

		/// <summary>
		/// Verifies that pie slices include only the outer arc and begin
		/// at the chart center.
		/// </summary>
		[Fact]
		public void PiePath_ContainsOuterArcOnly()
		{
			var slice = new DonutSlice("Pie", 50, 0, 90, 90, 0, "#00FF00");
			var path = slice.PathData;

			path.ShouldStartWith("M 100 100");
			path.ShouldContain("A 90 90");
		}

		/// <summary>
		/// Ensures that pie slices do not contain inner arcs,
		/// since their inner radius is zero.
		/// </summary>
		[Fact]
		public void PiePath_DoesNotContainInnerArc()
		{
			var slice = new DonutSlice("Pie", 25, 0, 120, 90, 0, "#EEEEEE");
			slice.PathData.ShouldNotContain("A 70 70");
		}

		/// <summary>
		/// Confirms that a slice always produces a non‑empty SVG path string.
		/// </summary>
		[Fact]
		public void Slice_HasNonEmptyPath()
		{
			var slice = new DonutSlice("Basic", 10, 0, 45, 90, 70, "#FF0000");
			slice.PathData.ShouldNotBeNullOrWhiteSpace(slice.PathData);
		}

		/// <summary>
		/// Validates that the slice constructor correctly assigns
		/// label, value, color, and CSS class properties.
		/// </summary>
		[Fact]
		public void Slice_SetsBasicProperties()
		{
			var slice = new DonutSlice("Test", 10, 0, 90, 90, 70, "#FF0000");

			slice.Label.ShouldBe("Test");
			slice.Value.ShouldBe(10);
			slice.Color.ShouldBe("#FF0000");
			slice.CssClass.ShouldBe("donut-slice");
		}
	}
}