using Microsoft.VisualStudio.TestTools.UnitTesting;
using BlazorControls.Components;

namespace BlazorControls.Components.Tests
{
	/// <summary>
	/// A suite of geometry‑focused tests validating the SVG path output
	/// generated by <see cref="DonutSlice"/>. These tests ensure correct
	/// construction of inner/outer arcs, pie vs donut behavior, and
	/// full‑circle rendering logic.
	/// </summary>
	[TestClass]
	public class DonutChartGeometryTests
	{
		/// <summary>
		/// Ensures that donut slices include both the outer arc
		/// (radius = outer radius) and the inner arc (radius = inner radius).
		/// </summary>
		[TestMethod]
		public void DonutPath_ContainsInnerAndOuterArcs()
		{
			var slice = new DonutSlice("Donut", 50, 0, 90, 90, 70, "#0000FF");
			var path = slice.PathData;

			Assert.Contains("A 90 90", path);
			Assert.Contains("A 70 70", path);
		}

		/// <summary>
		/// Verifies that donut slices do not begin at the chart center,
		/// which would indicate incorrect path construction.
		/// </summary>
		[TestMethod]
		public void DonutPath_DoesNotStartAtCenter()
		{
			var slice = new DonutSlice("Donut", 10, 0, 60, 90, 70, "#123456");
			Assert.DoesNotStartWith("M 100 100", slice.PathData);
		}

		/// <summary>
		/// Confirms that a full‑circle donut slice uses two outer arcs
		/// and two inner arcs to complete the shape.
		/// </summary>
		[TestMethod]
		public void FullCircleDonut_UsesTwoInnerAndTwoOuterArcs()
		{
			var slice = new DonutSlice("Full", 100, 0, 360, 90, 70, "#654321");
			var path = slice.PathData;

			Assert.AreEqual(2, path.Split("A 90 90").Length - 1);
			Assert.AreEqual(2, path.Split("A 70 70").Length - 1);
		}

		/// <summary>
		/// Ensures that a full‑circle pie slice (inner radius = 0)
		/// uses exactly two outer arcs to complete the circle.
		/// </summary>
		[TestMethod]
		public void FullCirclePie_UsesTwoOuterArcs()
		{
			var slice = new DonutSlice("FullPie", 100, 0, 360, 90, 0, "#123456");
			Assert.AreEqual(2, slice.PathData.Split("A 90 90").Length - 1);
		}

		/// <summary>
		/// Verifies that pie slices include only the outer arc and begin
		/// at the chart center.
		/// </summary>
		[TestMethod]
		public void PiePath_ContainsOuterArcOnly()
		{
			var slice = new DonutSlice("Pie", 50, 0, 90, 90, 0, "#00FF00");
			var path = slice.PathData;

			StringAssert.StartsWith(path, "M 100 100");
			Assert.Contains("A 90 90", path);
		}

		/// <summary>
		/// Ensures that pie slices do not contain inner arcs,
		/// since their inner radius is zero.
		/// </summary>
		[TestMethod]
		public void PiePath_DoesNotContainInnerArc()
		{
			var slice = new DonutSlice("Pie", 25, 0, 120, 90, 0, "#EEEEEE");
			Assert.DoesNotContain("A 70 70", slice.PathData);
		}

		/// <summary>
		/// Confirms that a slice always produces a non‑empty SVG path string.
		/// </summary>
		[TestMethod]
		public void Slice_HasNonEmptyPath()
		{
			var slice = new DonutSlice("Basic", 10, 0, 45, 90, 70, "#FF0000");
			Assert.IsFalse(string.IsNullOrWhiteSpace(slice.PathData));
		}

		/// <summary>
		/// Validates that the slice constructor correctly assigns
		/// label, value, color, and CSS class properties.
		/// </summary>
		[TestMethod]
		public void Slice_SetsBasicProperties()
		{
			var slice = new DonutSlice("Test", 10, 0, 90, 90, 70, "#FF0000");

			Assert.AreEqual("Test", slice.Label);
			Assert.AreEqual(10, slice.Value);
			Assert.AreEqual("#FF0000", slice.Color);
			Assert.AreEqual("donut-slice", slice.CssClass);
		}
	}
}